### ISSUE TITLE
Apontamentos Review

### ISSUE THREAD

**Issue by Nicolas-Coradassi-Ferreira** [Nicolas-Coradassi-Ferreira/Contatos-Persistence#1]
Comenta as correção ai pae, que crio branch e corrijo

**Comment by MarcosVCeo** [comment]
É melhor criar uma classe service para não deixar uma entidade com esses tipos de responsabilidades que não devem ser dela 
![image](https://github.com/Nicolas-Coradassi-Ferreira/Contatos-Persistence/assets/25181950/3e23394b-c583-4ab7-a23a-92d5874c15a7)

**Comment by MarcosVCeo** [comment]
Por que é necessário chamar o metodo` formatarTelefone` explicitamente sempre que ele vai ser usado? isso não me cheira bem

![image](https://github.com/Nicolas-Coradassi-Ferreira/Contatos-Persistence/assets/25181950/ec0935c9-c6ca-46e2-abf3-9114a620c4f4)

provavelmente seja mais interessante você já inserir os telefones formatados na entidade Contato, muito provavelmente já o formatando no próprio construtor

**Comment by MarcosVCeo** [comment]
essa regra para salvar um novo contato ficaria melhor se isolada dentro de uma service e o método receber o próprio `NovoDadosContato` fazendo o tratamento dentro da própria service

![image](https://github.com/Nicolas-Coradassi-Ferreira/Contatos-Persistence/assets/25181950/26953fbe-c7bc-44fb-bf49-2429fa65a945)

**Comment by MarcosVCeo** [comment]
Capturar qualquer tipo de exceção e tratar todos da mesma forma me parece errado, deveria ser mais descritivo o que realmente está acontecendo

![image](https://github.com/Nicolas-Coradassi-Ferreira/Contatos-Persistence/assets/25181950/8dfc8106-7ba8-4912-a653-9c4a0842b34e)

E o HTML diz que foi possível realizar operação, o correto não seria dizer que não foi possível?

![image](https://github.com/Nicolas-Coradassi-Ferreira/Contatos-Persistence/assets/25181950/67e09a09-318d-4e4a-aeae-d3a60d947da7)

**Comment by MarcosVCeo** [comment]
durante todo o código é usado a tipagem de tipos o que não está errado, porem não é necessário na maioria dos casos, utilizar var aonde possível

**Comment by Nicolas-Coradassi-Ferreira** [comment]
belezinha Marcos, fazendo as correções!

**Comment by Nicolas-Coradassi-Ferreira** [comment]
Correções feitas, aguardando review!!
